import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Activity, ShieldCheck, Timer, ShieldAlert, HelpCircle, Layers } from "lucide-react";
import toolsRegistry from "@/lib/tools-registry.json";
import CategoryToolSearchGrid from "@/components/tools/CategoryToolSearchGrid";
import fs from "fs";
import path from "path";

export async function generateMetadata(): Promise<Metadata> {
  const category = "health-tools";
  const categoryImagePath = path.join(process.cwd(), "public", "images", "categories", category);
  const webpCategoryPath = `${categoryImagePath}.webp`;
  const jpgCategoryPath = `${categoryImagePath}.jpg`;
  
  const featuredImage = fs.existsSync(webpCategoryPath)
    ? `https://www.twistertools.com/images/categories/${category}.webp`
    : fs.existsSync(jpgCategoryPath)
      ? `https://www.twistertools.com/images/categories/${category}.jpg`
      : "https://www.twistertools.com/images/og-default.jpg";

  return {
    title: "Health, Fitness & Biological Utilities",
    description: "Fast, privacy-first body composition calculators, athletic performance estimators, sleep and metabolic trackers, and clinical wellness utilities.",
    keywords: ["bmi calculator", "tdee calculator", "calorie deficit", "body fat percentage", "target heart rate zones", "sleep cycle tracker", "health tools", "twistertools"],
    alternates: {
      canonical: "https://www.twistertools.com/tools/health-tools",
    },
    openGraph: {
      title: "Health, Fitness & Biological Utilities - TwisterTools",
      description: "Fast, privacy-first body composition calculators, athletic performance estimators, sleep and metabolic trackers, and clinical wellness utilities.",
      url: "https://www.twistertools.com/tools/health-tools",
      siteName: "TwisterTools",
      type: "website",
      images: [
        {
          url: featuredImage,
          width: 1200,
          height: 630,
          alt: "Health, Fitness & Biological Utilities",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: "Health, Fitness & Biological Utilities - TwisterTools",
      description: "Fast, privacy-first body composition calculators, athletic performance estimators, sleep and metabolic trackers, and clinical wellness utilities.",
      images: [featuredImage],
    },
  };
}

const healthMetadata = {
  name: "Health, Fitness & Biological Utilities",
  icon: "Activity",
  description: "Fast, privacy-first body composition calculators, athletic performance estimators, sleep and metabolic trackers, and clinical wellness utilities.",
  detailedGuide: "Optimize your wellness journey with client-side health calculators. All biometric data is processed purely in your browser session for complete privacy.",
  cards: [
    {
      title: "100% Private Biometric Calculations",
      icon: "ShieldCheck",
      content: "Your health data (height, weight, age, activity level) is deeply personal. Our architecture guarantees that no biometric inputs, calculations, or results are ever sent to a server. Everything runs entirely in your browser thread, keeping your health information completely private."
    },
    {
      title: "Clinical & Athletic Estimation Engines",
      icon: "Activity",
      content: "Calculate key health metrics like Body Mass Index (BMI), Total Daily Energy Expenditure (TDEE), target heart rate zones, and body fat percentages. Our tools use established equations (such as Harris-Benedict, Mifflin-St Jeor, and Karvonen formulas) to provide precise estimations for fitness planning."
    },
    {
      title: "Fitness & Metabolic Tracking",
      icon: "Timer",
      content: "Plan your nutrition, weight loss targets, or athletic conditioning with metabolic calculators. Easily determine calorie deficits, optimal macro-nutrient splits, and aerobic training intensities tailored to your custom physiology."
    },
    {
      title: "Medical & Wellness Disclaimer",
      icon: "ShieldAlert",
      content: "All calculations, estimations, and reports generated by our health tools (including BMI, body fat, TDEE, BAC, calorie deficits, and heart rate zones) are for educational and informational estimation purposes only. They do not constitute professional medical advice, diagnosis, or clinical treatment, and should not be used as a substitute for professional healthcare consultation."
    }
  ],
  faqs: [
    {
      q: "Are my height, weight, or health inputs saved anywhere?",
      a: "Never. All biometric data and calculation inputs remain strictly local inside your browser's memory. We do not store or transmit any health or personal details."
    },
    {
      q: "Are these calculators a substitute for clinical diagnostics?",
      a: "No. These tools provide estimations based on standard mathematical formulas (like BMI and TDEE equations). They are not clinical diagnostic tools and should not replace professional medical evaluations or personalized advice from a doctor."
    },
    {
      q: "Which formulas are used to estimate daily calories and BMR?",
      a: "Our metabolic estimators use standard, clinically-validated equations including the Mifflin-St Jeor and Harris-Benedict formulas to compute Basal Metabolic Rate (BMR) and Total Daily Energy Expenditure (TDEE)."
    }
  ]
};

export default function HealthToolsCategoryPage() {
  const categoryTools = toolsRegistry
    .map((tool, idx) => ({ ...tool, originalIndex: idx }))
    .filter((tool) => tool.category === "health-tools")
    .sort((a, b) => {
      const aFeatured = a.isFeatured ? 1 : 0;
      const bFeatured = b.isFeatured ? 1 : 0;
      if (aFeatured !== bFeatured) return bFeatured - aFeatured;
      return b.originalIndex - a.originalIndex;
    });

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 pb-16 text-slate-800 dark:text-slate-200">
      {/* Header: Slate-to-Indigo Title Bar */}
      <header className="relative overflow-hidden bg-slate-900 text-white border-b border-indigo-700/50">
        <div className="absolute inset-0 z-0 overflow-hidden">
          <Image
            src="/images/og-hero.jpg"
            alt="TwisterTools Background Visual"
            fill
            priority
            className="object-cover object-center opacity-50 mix-blend-luminosity"
            sizes="100vw"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-900/80 to-indigo-950/85" />
        </div>
        <div className="relative z-10 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
          {/* Navigation Breadcrumbs */}
          <div className="flex items-center gap-1 text-indigo-100 text-xs md:text-sm font-medium flex-wrap overflow-x-auto whitespace-nowrap scrollbar-none">
            <Link href="/" className="hover:text-white transition-colors max-w-[130px] sm:max-w-[200px] md:max-w-none truncate">
              Home
            </Link>
            <span>/</span>
            <Link href="/tools" className="hover:text-white transition-colors max-w-[130px] sm:max-w-[200px] md:max-w-none truncate">
              Tools
            </Link>
            <span>/</span>
            <span className="text-white font-semibold max-w-[130px] sm:max-w-[200px] md:max-w-none truncate">
              {healthMetadata.name}
            </span>
          </div>

          {/* Title Block */}
          <div className="flex items-start gap-4 mt-6">
            <div className="bg-white/20 backdrop-blur-sm p-3.5 flex items-center justify-center text-white shadow-lg rounded-2xl w-14 h-14 flex-shrink-0">
              <Activity className="w-8 h-8" />
            </div>
            <div className="flex-1 min-w-0">
              <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight text-white leading-tight">
                {healthMetadata.name}
              </h1>
              <p className="text-sm md:text-base text-indigo-100 mt-2 max-w-3xl leading-relaxed">
                {healthMetadata.description}
              </p>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content Workspace Container */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-10 space-y-12">
        
        {/* YMYL Amber Medical Disclaimer Banner */}
        <div className="bg-amber-50 border border-amber-200 text-amber-900 rounded-xl p-4 flex items-start gap-3 text-sm">
          <ShieldAlert className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <strong className="font-semibold block mb-1">Medical Disclaimer</strong>
            <p>
              Calculations and estimations provided by these tools (including BMI, TDEE, BAC, calorie deficits, heart rate zones, and other health estimators) are for educational and informational purposes only. They do not constitute professional medical advice, diagnosis, or clinical treatment. Always consult a qualified healthcare provider before making medical decisions or changes to your fitness and nutrition plans.
            </p>
          </div>
        </div>

        {/* Dynamic Search grid component */}
        <CategoryToolSearchGrid
          tools={categoryTools}
          categorySlug="health-tools"
        />

        {/* Below-The-Fold SEO Content Layout */}
        <div className="border-t border-slate-200 dark:border-slate-800 pt-12 space-y-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {healthMetadata.cards.map((card, idx) => {
              const CardIcon =
                card.icon === "ShieldCheck" ? ShieldCheck :
                card.icon === "Activity" ? Activity :
                card.icon === "Timer" ? Timer :
                card.icon === "ShieldAlert" ? ShieldAlert : Layers;

              return (
                <div
                  key={idx}
                  className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-8 shadow-sm space-y-4"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-9 h-9 rounded-xl bg-indigo-100 dark:bg-indigo-950/80 flex items-center justify-center flex-shrink-0 text-indigo-600 dark:text-indigo-400">
                      <CardIcon className="w-5 h-5" />
                    </div>
                    <h2 className="text-lg md:text-xl font-bold text-slate-900 dark:text-white">
                      {card.title}
                    </h2>
                  </div>
                  <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
                    {card.content}
                  </p>
                </div>
              );
            })}
          </div>

          {/* Full-width FAQ SEO Card */}
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-8 shadow-sm space-y-6">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-indigo-100 dark:bg-indigo-950/80 flex items-center justify-center flex-shrink-0 text-indigo-600 dark:text-indigo-400">
                <HelpCircle className="w-5 h-5" />
              </div>
              <h2 className="text-lg md:text-xl font-bold text-slate-900 dark:text-white">
                Frequently Asked Questions
              </h2>
            </div>
            <dl className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
              {healthMetadata.faqs.map((faq, idx) => (
                <div key={idx} className="space-y-2">
                  <dt className="font-semibold text-slate-900 dark:text-white text-sm">
                    {faq.q}
                  </dt>
                  <dd className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                    {faq.a}
                  </dd>
                </div>
              ))}
            </dl>
          </div>
        </div>
      </div>
    </div>
  );
}
